### ISSUE TITLE
"Circular reference" error for multiple references to the same objects

### ISSUE THREAD

**Issue by jens-duttke** [nervgh/object-traverse#2]
This code returns a "Circular reference" error, even if there is no circular reference, just multiple references to another object, which is absolutely valid:
```
var x = {};

var object = {
    a: x,
    b: x
};

Object.traverse(object, function(node, value, key, path, depth) {
    console.log(path.join('.'), value);
});
```
You should check if any parent value equals the current value, and not if any already processed node of the whole tree matches.

**Comment by nervgh** [comment]
@jens-duttke thank you for reporting this issue :+1:  I will try to fix it at [recursive-iterator](https://github.com/nervgh/recursive-iterator) project.

**Comment by nervgh** [comment]
It was moved to https://github.com/nervgh/recursive-iterator/issues/8
